version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-demo-app1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-n65uovi0uzpm"
s3_prefix = "sam-demo-app1"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

